### PR TITLE
fix some small issues in inmemory storage placevisit

### LINKED ISSUE #59: fix inmemory PlaceVisit bugs
-issue where updateOrAddPlaceVisitModel does not add new HashMap when adding a PlaceVisitModel object if there are no other PlaceVisitModel objects in storage with the same tripId

-listTripPlaceVisits only returns placeVisit objects marked as YES or MAYBE when should return all PlaceVisit objects associated with the trip

### PR DESCRIPTION
**Pull request by cli1903**
-remove the check for user status when listing trips
-small bug where I didn't put the new hashmap into storage when adding a placevisit for a new trip

### CODE REVIEW

File: frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java [hunk 1]
```diff
@@ -71,6 +71,7 @@ public boolean updateUserMarkOrAddPlaceVisit(
       if (placesMap == null) {
         Map<String, PlaceVisitModel> newPlaceMap = new ConcurrentHashMap<>();
         newPlaceMap.put(placeVisit.placeId(), placeVisit);
+        storage.put(placeVisit.tripId(), newPlaceMap);
```
Comment (bsidhom) [inline frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java]: For some reason I thought we had switched this to `ConcurrentHashMap`.

Comment (bsidhom) [reply frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java]: Looks like this is a concurrent hash map, and we're using it without map-level synchronization in `addPlaceVisit` above. That means this synchronized block is not safe against interleavings from other methods. (In particular, it looks like `ConcurrentHashMap` uses bucket-level synchronization, though that's an implementation detail and not part of the public interface.)

This will need to be updated to use `compute` or similar instead of a `synchronized` block.

I'm also not able to add a comment about it on the line above, but there's a weird catch/rethrow structure in `addPlaceVisit` that should be simplified to a direct throw. (The `try/catch` structure should be removed entirely.)

**Review by bsidhom — CHANGES_REQUESTED** [review]

File: frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java (hunk 1 above)
Comment (cli1903) [reply frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java]: I was doing a catch rethrow thing because within compute, only Runtime Exceptions can be thrown, so I couldn't directly throw a PlaceAlreadyExists exception within the compute function

Comment (bsidhom) [reply frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java]: Hmm...that makes sense, but the intent is difficult to read. I would have probably minted a new runtime exception type for that and then caught only that and translated it appropriately. Don't bother doing that here, but please add a comment where you throw the runtime exception and explain why you're doing so.

File: frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java [hunk 2]
```diff
@@ -30,13 +25,19 @@ public void addPlaceVisit(PlaceVisitModel placeVisit) throws PlaceVisitAlreadyEx
...
+          // cannot throw checked exception in here so wrap in RuntimeException
           throw new RuntimeException(new PlaceVisitAlreadyExistsException("PlaceVisit "
               + placeVisit.name() + " already exists for trip " + placeVisit.tripId()));
         }
         placesMap.put(placeVisit.placeId(), placeVisit);
         return placesMap;
       });
     } catch (RuntimeException e) {
+      /**
+       * check if RuntimeException is actually because of PlaceVisitAlreadyExistsException
```
Comment (bsidhom) [inline frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java]: Extra-nitty nit: use `//`-style comments here

File: frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java [hunk 3]
```diff
@@ -66,23 +67,31 @@ public void removePlaceVisit(String tripId, String placeId) throws PlaceVisitNot
...
-        placesMap.put(placeVisit.placeId(),
-            placesMap.get(placeVisit.placeId()).toBuilder().setUserMark(newStatus).build());
-        return true;
-      } else {
-        placesMap.put(placeVisit.placeId(), placeVisit);
-        return false;
-      }
-    }
+
+    boolean[] alreadyInStorage = new boolean[1];
```
Comment (bsidhom) [inline frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java]: Nice hack. 😉 

This would be more readable as an `AtomicBoolean`.

```java
AtomicBoolean alreadyInStorage = new AtomicBoolean(false);
...
if (placesMap.get(placeVisit.placeId()) != null) {
  ...
  alreadyInStorage.set(true);
}
...
return alreadyInStorage.get();
```

File: frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java [hunk 4]
```diff
@@ -66,23 +67,31 @@ public void removePlaceVisit(String tripId, String placeId) throws PlaceVisitNot
...
+    alreadyInStorage[0] = false;
+
+    storage.compute(placeVisit.tripId(), (tripKey, placesMap) -> {
+        if (placesMap == null) {
```
Comment (bsidhom) [inline frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java]: Interesting idea--I believe this whole method is done under bucket-level synchronization, so this should actually update both the inner and outer map atomically.

However, it might be a bit more readable (and possibly performant in limiting cases) if you performed the inner and outer map updates separately. Doing so is safe as long as we don't care about making the 2 levels of changes atomically. Should be safe in our case since, if the trip is deleted from the outer map in the middle of this, we're just updating an unreferenced map that will eventually be garbage collected.

To restructure this way, you can just immediately return the place map after construction. In that case, you'd actually use `computeIfAbsent`:

```java
Map<String, PlaceVisitModel placeMap = storage.computeIfAbsent(placeVisit.tripId(), (tripKey, placesMap) -> new ConcurrentHashMap());
// Then continue to use placeMap below.
```

Also a small point about concurrency here: the since you're effectively holding two locks here (on the outer and one on the inner map, below), it's important to consider the possibility of deadlock, which is possible whenever locks are acquired in a cycle. This seems to be safe here since you always acquire the locks in the same order: outer, inner.

File: frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java [hunk 5]
```diff
@@ -66,23 +67,31 @@ public void removePlaceVisit(String tripId, String placeId) throws PlaceVisitNot
...
+          Map<String, PlaceVisitModel> newPlaceMap = new ConcurrentHashMap<>();
+          newPlaceMap.put(placeVisit.placeId(), placeVisit);
+          return newPlaceMap;
+        }
+        
+        if (placesMap.get(placeVisit.placeId()) != null) {
```
Comment (bsidhom) [inline frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java]: The null-check and subsequent get-and-update checks here are not currently atomic. You'll need to perform these in a compute function, e.g.:

```java
placesMap.compute(placeVisit.placeId(), (placeId, place) -> {
  if (place != null) {
    alreadyInStorage.set(true);
    // TODO: Update existing place and return.
  } else {
    // TODO: return a new place with the correct value.
  }
  
});
```

File: frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java [hunk 6]
```diff
@@ -1,24 +1,24 @@
...
 public class InMemoryPlaceVisitStorage implements PlaceVisitStorage {
   // <tripId, placeId, PlaceVisitModel>
-  Map<String, Map<String, PlaceVisitModel>> storage = new ConcurrentHashMap<>();
+  Map<String, Map<String, PlaceVisitModel>> placesByPlaceIdByTripId = new ConcurrentHashMap<>();
 
   @Override
   public void addPlaceVisit(PlaceVisitModel placeVisit) throws PlaceVisitAlreadyExistsException {
     try {
-      storage.compute(placeVisit.tripId(), (tripKey, placesMap) -> {
+      placesByPlaceIdByTripId.compute(placeVisit.tripId(), (tripKey, placesMap) -> {
```
Comment (bsidhom) [inline frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java]: Nit: “by trip ID, by place ID” makes more sense since this is the order of access (it currently reads in an inverted fashion).

File: frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java [hunk 7]
```diff
@@ -61,42 +59,34 @@ public void removePlaceVisit(String tripId, String placeId) throws PlaceVisitNot
...
-        }
-        
-        return placesMap;
+    placesMap.compute(placeVisit.placeId(), (placeKey, place) -> {
+      if (place != null) {
+        PlaceVisitModel updatedPlace = place.toBuilder().setUserMark(newStatus).build();
+        alreadyInStorage.set(true);
+        return updatedPlace;
+      } else {
+        return placeVisit;
```
Comment (bsidhom) [inline frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java]: Does the given place visit have the current user mark in this case? If so, feel free to resolve this. If not, I assume you’ll need to set the mark here.

**Review by bsidhom — DISMISSED** [review]
LGTM after two minor comments.

File: frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java [hunk 8]
```diff
@@ -60,41 +59,40 @@ public void removePlaceVisit(String tripId, String placeId) throws PlaceVisitNot
...
+    AtomicBoolean alreadyInStorage = new AtomicBoolean(false);
+
+    Map<String, PlaceVisitModel> placesMap = placesByTripIdByPlaceId.computeIfAbsent(
+        placeVisit.tripId(), (tripKey) -> new ConcurrentHashMap<>());
+
+    placesMap.compute(placeVisit.placeId(), (placeKey, place) -> {
+      if (place != null) {
+        PlaceVisitModel updatedPlace = place.toBuilder().setUserMark(newStatus).build();
+        alreadyInStorage.set(true);
+        return updatedPlace;
```
Comment (chuckluv) [inline frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java:78]: I'm confused, how can you return a PlaceVisitModel when the return type is a boolean

File: frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java [hunk 9]
```diff
@@ -60,41 +59,40 @@ public void removePlaceVisit(String tripId, String placeId) throws PlaceVisitNot
...
-      if (placesMap == null) {
-        Map<String, PlaceVisitModel> newPlaceMap = new ConcurrentHashMap<>();
-        newPlaceMap.put(placeVisit.placeId(), placeVisit);
-        return false;
-      }
-      if (placesMap.get(placeVisit.placeId()) != null) {
-        placesMap.put(placeVisit.placeId(),
-            placesMap.get(placeVisit.placeId()).toBuilder().setUserMark(newStatus).build());
-        return true;
+    AtomicBoolean alreadyInStorage = new AtomicBoolean(false);
```
Comment (chuckluv) [inline frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java:69]: What's the purpose in using AtomicBoolean instead of a regular boolean

**Review by chuckluv — DISMISSED** [review]

File: frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java (hunk 8 above)
Comment (cli1903) [reply frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java:78]: the compute function basically just updates/adds an entry in the hashmap so the lambda function that is passed into the compute function has to return the object that you want to store as the value - it won't return from the overall function

File: frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java (hunk 9 above)
Comment (cli1903) [reply frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java:69]: you can't change the value of a variable within a lambda function so I couldn't use a regular boolean variable. The value within the AtomicBoolean can be updated though

**Review by bsidhom — DISMISSED** [review]
LGTM

File: frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java [hunk 10]
```diff
@@ -1,10 +1,16 @@
 package com.google.tripmeout.frontend.storage;
 
+import com.google.tripmeout.frontend.PlaceVisitModel;
+import com.google.tripmeout.frontend.error.PlaceVisitAlreadyExistsException;
+import com.google.tripmeout.frontend.error.PlaceVisitNotFoundException;
+import com.google.tripmeout.frontend.error.TripNotFoundException;
+
```
Comment (bsidhom) [inline frontend/src/main/java/com/google/tripmeout/frontend/storage/InMemoryPlaceVisitStorage.java]: There's something weird here. Not sure why the `com.google.tripmeout.frontend` packages are getting split around the `java.*` imports. Please make sure to run the formatter in any case.

**Review by bsidhom — DISMISSED** [review]
LGTM modulo weird import ordering.

**Review by anfee1 — APPROVED** [review]
LGTM

**Review by KoopaKing — APPROVED** [review]

**Review by bsidhom — APPROVED** [review]
