### PR TITLE
Fix InMemoryTripService to correctly assign UUIDs on creation

### LINKED ISSUE #53: Fix the Dart InMemoryTripService
The Dart in memory trip service does not correctly populate uuids. This behavior seems to diverge from the expected REST API behavior.

This should be fixed.

### PR DESCRIPTION
**Pull request by KoopaKing**
Fixes #53

### CODE REVIEW

File: frontend/ui/test/services/in_memory_trip_service_test.dart [hunk 1]
```diff
@@ -16,19 +16,19 @@ void main() {
...
     var tripService = InMemoryTripService();
-    var trip1 = Trip(id: 'id1', name: 'name1');
-    var trip2 = Trip(id: 'id2', name: 'name2');
+    var trip1 = Trip(name: 'name1');
+    var trip2 = Trip(name: 'name2');
     // do async setup inside a setUp lambda because group lambdas cant be async
-    setUp(() async {
-      await tripService.createTrip(trip1);
-      await tripService.createTrip(trip2);
+    setUpAll(() async {
```
Comment (KoopaKing) [inline frontend/ui/test/services/in_memory_trip_service_test.dart:22]: I didn't realize `setUp` runs before each test, `setUpAll` runs for all tests in the group. So this is a fix of that too.

**Review by anfee1 — DISMISSED** [review]
The ?? in the model location and trip are saying do nothing if a null value right?

**Review by cli1903 — DISMISSED** [review]

**Review by chuckluv — DISMISSED** [review]

File: frontend/ui/lib/model/trip.dart [hunk 2]
```diff
@@ -1,9 +1,18 @@
 import 'package:tripmeout/model/location.dart';
 
 class Trip {
-  Trip({this.name, this.id, this.location});
+  Trip({this.name = "", this.id = "", location})
```
Comment (bsidhom) [inline frontend/ui/lib/model/trip.dart]: Can you mark these fields as nullable rather than giving them empty string values?

File: frontend/ui/lib/model/trip.dart [hunk 3]
```diff
@@ -1,9 +1,18 @@
...
+      : location = location ?? Location();
 
   final String name;
   final String id;
   final Location location;
+
+  static Trip from(Trip trip, {name, id, location}) {
+    return Trip(
+      name: name ?? trip.name,
```
Comment (bsidhom) [inline frontend/ui/lib/model/trip.dart]: I'm guessing that `""` will always be selected over `trip.name` here and this only does the right thing if `name` is null?

Comment (KoopaKing) [reply frontend/ui/lib/model/trip.dart]: Yeah, but non-positional arguments are optional here. The goal of this function is to provide clone/override functionality all in one. So essentially:
```dart
Trip trip1 = Trip(name: "my trip", id: "1");
// trip1 == { name: "my trip", id: "1", location: { latitude: 0, longitude: 0 } }
Trip otherTrip1 = Trip.from(trip1);
// otherTrip1 == { name: "my trip", id: "1", location: { latitude: 0, longitude: 0 }  }
Trip trip2 = Trip.from(trip1, id: "2");
// trip2 == { name: "my trip", id: "2", location: { latitude: 0, longitude: 0 }  }
```

This brings up an important point though, that I should write some tests for this...

File: frontend/ui/lib/model/trip.dart (hunk 2 above)
Comment (KoopaKing) [reply frontend/ui/lib/model/trip.dart]: Yeah, before they were nullable, I just prefer the empty string behavior over null. I'm not super opinionated though.

**Comment by KoopaKing** [comment]
> The ?? in the model location and trip are saying do nothing if a null value right?

In Dart the `??` operator is do something if not null. It can just replaces the ternary operator or if statements for certain operations.

The following three functions do the same thing:
```dart
static String defaultValue = "blahblahblah";

static String usingDoubleQuestionMarks(String nullable) {
  return nullable ?? defaultValue;
}

static String usingTernaryOperator(String nullable) {
  return (nullable != null) ? nullable : defaultValue;
}

static String usingIfStatement(String nullable) {
  if (nullable != null) {
    return nullable;
  } else {
    return defaultValue;
  }
}
```

https://dart.dev/guides/language/language-tour#conditional-expressions

File: frontend/ui/lib/model/trip.dart (hunk 3 above)
Comment (bsidhom) [reply frontend/ui/lib/model/trip.dart]: Got it. I also just realized that `name` here is resolved from the static method param rather than an existing trip entry (in which case `null` is presumably the default).

I was actually going to mention that I don't usually like to add tests to "dumb" value classes but I'd feel compelled to do so in this case mostly because I don't know dart. Then I figured you probably knew what you were doing and I'd defer to you. 😉

**Review by bsidhom — DISMISSED** [review]
LGTM

**Review by chuckluv — APPROVED** [review]

**Review by cli1903 — APPROVED** [review]
