### PR TITLE
Fixing flutter comments

### LINKED ISSUE #67: Fixing Style on Flutter Pages
Making sure to use the theme styles associated with pages and adjust the sizing for the widgets on each page

### PR DESCRIPTION
**Pull request by anfee1**
Closes #67 

Comments are located in #45

### CODE REVIEW

**Review by KoopaKing — APPROVED** [review]

File: frontend/ui/lib/themes/default_theme.dart [hunk 1]
```diff
@@ -1,7 +1,9 @@
...
 final ThemeData defaultTheme = ThemeData(
-  // TODO: customize me...
-  primaryColor: const Color(0xff526948),
-  accentColor: const Color(0xff6fa15a),
-);
+    // TODO: customize me...
+    primaryColor: const Color(0xff526948),
+    accentColor: const Color(0xff6fa15a),
+    buttonTheme: ButtonThemeData(
+      buttonColor: const Color(0xff6fa15a),
```
Comment (bsidhom) [inline frontend/ui/lib/themes/default_theme.dart:8]: I believe it's best practice to defer color choices (such as button color) to colors that have been defined elsewhere. For example, this should probably just reference `accentColor`. Be careful though, since the accent color is usually used to draw attention to a particular button _relative_ to others (i.e., you often only want a single button colored with the accent color (such a "submit" button on a form) and the rest to be relatively neutral). If you want to give a particular button accented color, you can do so by assigning it the accent color theme when you create it.

**Review by cli1903 — APPROVED** [review]

File: frontend/ui/lib/themes/default_theme.dart (hunk 1 above)
Comment (anfee1) [reply frontend/ui/lib/themes/default_theme.dart:8]: From what I am thinking in regards to the mocks I don't think this should be a problem since there shouldn't be too many buttons and the ones we are using should stand out since it's adding to the trip or submitting your trip.
